# Generated by Django 3.0.7 on 2020-06-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(verbose_name='balance')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.IntegerField(verbose_name='actual')),
                ('mes', models.DateField(verbose_name='mes')),
                ('planificado', models.IntegerField(verbose_name='planificado')),
                ('slug', models.SlugField(unique=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.Presupuesto')),
            ],
            options={
                'verbose_name': 'Presupuesto Mensual',
                'verbose_name_plural': 'Presupuestos Mensuales',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(verbose_name='balance')),
                ('beneficiario', models.CharField(max_length=50, verbose_name='beneficiario')),
                ('debito', models.BooleanField(default=True, verbose_name='débito')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('monto', models.IntegerField(verbose_name='monto')),
                ('slug', models.SlugField(unique=True)),
                ('transferencia', models.BooleanField(default=False, verbose_name='transferencia')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Categoria')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.Cuenta')),
                ('presupuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finanzas.PresupuestoMensual')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='prespuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.Presupuesto'),
        ),
    ]
